name: 'Plugin'

on:
  push:

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-plugin:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - x86

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgGitCommitId: '927006b24c3a28dfd8aa0ec5f8ce43098480a7f1'
          vcpkgTriplet: '${{ matrix.platform }}-windows'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}

      - name: Install MSBuild integration
        run: vcpkg integrate install

      - name: MSBuild
        run: |
          msbuild `
            -m `
            -property:Configuration="Release" `
            -property:Platform="${{ matrix.platform }}" `
            -property:OutDir="${{ matrix.platform }}"

      - name: Prepare Artifact
        run: |
          New-Item -Path Artifact -ItemType Directory
          New-Item -Path Artifact/Plugins -ItemType Directory
          Copy-Item -Path ${{ matrix.platform }}/*.tvtp -Destination Artifact/Plugins/
          Copy-Item -Path ${{ matrix.platform }}/*.dll -Destination Artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'TVTestRemoteController_${{ matrix.platform }}'
          if-no-files-found: 'error'
          path: 'Artifact/'

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path Artifact/* -DestinationPath TVTestRemoteController_${{ matrix.platform }}.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'TVTestRemoteController_${{ matrix.platform }}.zip'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
